/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DrawableComponent {
    /**
    * height
    */
    'height': string;
    /**
    * width
    */
    'width': string;
  }
}

declare global {


  interface HTMLDrawableComponentElement extends Components.DrawableComponent, HTMLStencilElement {}
  var HTMLDrawableComponentElement: {
    prototype: HTMLDrawableComponentElement;
    new (): HTMLDrawableComponentElement;
  };
  interface HTMLElementTagNameMap {
    'drawable-component': HTMLDrawableComponentElement;
  }
}

declare namespace LocalJSX {
  interface DrawableComponent extends JSXBase.HTMLAttributes<HTMLDrawableComponentElement> {
    /**
    * height
    */
    'height'?: string;
    /**
    * width
    */
    'width'?: string;
  }

  interface IntrinsicElements {
    'drawable-component': DrawableComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


